[package]
name = "shsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.2"
crossterm = "0.27.0"
rev_lines = "0.3.0"
regex = "1.10.3"
glob = "0.3.1"
